// List of people
// Originally used JSON, but it wasn't worth the CORS issues
let people = [
  // Person object
  {
    "FN": "Flynn", // First Name
    "LN": "Burrell", // Last name
    "BD": "2008", // Year of birth
    "HC": "blonde", // Hair Colour
    "EC": "green", // Eye Colour
    "HT": "5", // Height in feet
    "SC": "White", // Skin Colour
    "NS": "0", // Number of Siblings
    "PR": "together", // Parent relationship status
    "NG": "4", // Number of Grandparents
    "HA": "6 Beeche Place", // Home address
    "BF": "not sure", // Best Friend
    "IN": ["piano", "gaming", "vinyls"], // Interests x3
    "GL": "no", // Wears glasses
    "SX": "male", // Sex
    "AT": "cats", // Preffered animal
    "SP": "no", // Plays sports
    "WS": "yes", // Wears shorts often
    "HR": "curly", // Hair type
    "EA": "pierced", // Ears Pierced
    "Match": [0] // Score
  },
  {
    "FN":"Noah",
    "LN":"Dixon",
    "BD":"2008",
    "HC":"brown",
    "EC":"brown",
    "HT":"5",
    "SC":"white",
    "NS":"0",
    "PR":"separated",
    "NG":"2",
    "HA":"35A Waipa Street",
    "BF":"Phoenix",
    "IN":["military","gaming","rock climbing"],
    "GL":"no",
    "SX":"male",
    "AT":"cats",
    "SP":"yes",
    "WS":"no",
    "HR":"straight",
    "EA":"unpierced",
    "Match":[0]
  },
  {
    "FN": "Igor",
    "LN": "Komarov",
    "BD": "2009",
    "HC": "brown",
    "EC": "brown",
    "HT": "5",
    "SC": "White",
    "NS": "3",
    "PR": "married",
    "NG": "1",
    "HA": "27 noleen street",
    "BF": "Emma",
    "IN": ["art", "gaming", "nature"],
    "GL": "no",
    "SX": "male",
    "AT": "cats",
    "SP": "no",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Sophia",
    "LN": "Shen",
    "BD": "2008", 
    "HC": "Brown",
    "EC": "Brown",
    "HT": "5",
    "SC": "Yellow", 
    "NS": "5",
    "PR": "Dating",
    "NG": "5",
    "HA": "175 Chelsea View Drive",
    "BF": "Noa King",
    "IN": ["physics", "tennis", "math"],
    "GL": "no",
    "SX": "Female",
    "AT": "dogs",
    "SP": "yes",
    "WS": "no",
    "HR": "straight",
    "EA": "pierced",
    "Match": [0]
  },
  {
    "FN": "Uliana",
    "LN": "Kuznetsova",
    "BD": "2008",
    "HC": "brown",
    "EC": "brown",
    "HT": "5",
    "SC": "white",
    "NS": "1",
    "PR": "married",
    "NG": "1",
    "HA": "85 A Balmain road",
    "BF": "Dante",
    "IN": ["art", "badminton", "baking"],
    "GL": "sometimes",
    "SX": "female",
    "AT": "cats",
    "SP": "yes",
    "WS": "no",
    "HR": "straight",
    "EA": "pierced",
    "Match": [0]
  },
  {
    "FN": "Rein",
    "LN": "Balon",
    "BD": "2009",
    "HC": "Black",
    "EC": "brown",
    "HT": "5",
    "SC": "yellow",
    "NS": "0",
    "PR": "divorced",
    "NG": "4",
    "HA": "15 ian marwick",
    "BF": "rhea",
    "IN": ["movies", "badminton", "art"],
    "GL": "no",
    "SX": "female",
    "AT": "cats",
    "SP": "yes",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Brodie",
    "LN": "Roberts",
    "BD": "2008",
    "HC": "blonde",
    "EC": "blue",
    "HT": "5",
    "SC": "white",
    "NS": "2",
    "PR": "divorced",
    "NG": "4",
    "HA": "3/16 tamahere drive",
    "BF": "bradley",
    "IN": ["skibidi toilet", "gaming", "rizzing"],
    "GL": "no",
    "SX": "male",
    "AT": "cats",
    "SP": "no",
    "WS": "no",
    "HR": "wavy",
    "EA": "unpierced",
    "Match": [0]
  },
  { 
    "FN": "Locky",
    "LN": "Tuck",
    "BD": "2008",
    "HC": "brown",
    "EC": "hazel",
    "HT": "5",
    "SC": "white",
    "NS": "1",
    "PR": "married",
    "NG": "3",
    "HA": "4 menear lane",
    "BF": "brodie roberts",
    "IN": ["skibidi toilet", "gaming", "rizzing"],
    "GL": "no",
    "SX": "male",
    "AT": "dogs",
    "SP": "yes",
    "WS": "yes",
    "HR": "curly",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Jack",
    "LN": "Harris",
    "BD": "2008",
    "HC": "Black",
    "EC": "Brown",
    "HT": "5",
    "SC": "Yellow",
    "NS": "1",
    "PR": "Divorced",
    "NG": "2",
    "HA": "18 blundell place, chatswood",
    "BF": "Alexander Emelio Pavel Allan",
    "IN": ["gaming","anime","drawing"],
    "GL": "no",
    "SX": "male",
    "AT": "dogs",
    "SP": "yes",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Alex",
    "LN": "Allan",
    "BD": "2009",
    "HC": "black",
    "EC": "Grey",
    "HT": "5",
    "SC": "White",
    "NS": "1",
    "PR": "Divorced",
    "NG": "0",
    "HA": "12 Tilden ave Hillcrest",
    "BF": "Jack Harris",
    "IN": ["gaming","technology","drawing"],
    "GL": "no",
    "SX": "male",
    "AT": "cats",
    "SP": "no",
    "WS": "no",
    "HR": "curly",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Sergii",
    "LN": "Orekhivskyi",
    "BD": "2008",
    "HC": "brown",
    "EC": "brown",
    "HT": "6",
    "SC": "White",
    "NS": "1",
    "PR": "confused as teenagers",
    "NG": "2",
    "HA": "12 Tilden ave Hillcrest",
    "BF": "Hunter Burton",
    "IN": ["bomb","boom","women"],
    "GL": "yes",
    "SX": "male",
    "AT": "cats",
    "SP": "no",
    "WS": "yes",
    "HR": "wavy",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Noah",
    "LN": "Ah Ling",
    "BD": "2008",
    "HC": "black",
    "EC": "brown",
    "HT": "5",
    "SC": "yellow",
    "NS": "1",
    "PR": "not divorced (yet)",
    "NG": "3",
    "HA": "",
    "BF": "Luke Mathews",
    "IN": ["gaming","Gaming x2","gaming (more)"],
    "GL": "yes",
    "SX": "male",
    "AT": "dogs",
    "SP": "no",
    "WS": "yes",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Tom",
    "LN": "Campbell",
    "BD": "2008",
    "HC": "dirty blonde",
    "EC": "blue/green",
    "HT": "5",
    "SC": "White",
    "NS": "0",
    "PR": "married",
    "NG": "4",
    "HA": "Verbena Road",
    "BF": "Ariel Skudder",
    "IN": ["technology","music","gaming"],
    "GL": "no",
    "SX": "male",
    "AT": "cats",
    "SP": "no",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Jamie",
    "LN": "Langenhoven",
    "BD": "2008",
    "HC": "orange",
    "EC": "blue",
    "HT": "5",
    "SC": "White",
    "NS": "1",
    "PR": "married",
    "NG": "2",
    "HA": "Chatswood",
    "BF": "Tom Campbell",
    "IN": ["reading","gaming","platformers"],
    "GL": "no",
    "SX": "male",
    "AT": "cats",
    "SP": "no",
    "WS": "no",
    "HR": "wavy",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Phillip",
    "LN": "Alona",
    "BD": "2008",
    "HC": "black",
    "EC": "brown",
    "HT": "5",
    "SC": "caramel chocolate",
    "NS": "1",
    "PR": "married",
    "NG": "1",
    "HA": "21 toner road",
    "BF": "Arthur",
    "IN": ["Arthur","netflix","music"],
    "GL": "no",
    "SX": "male",
    "AT": "cats",
    "SP": "yes",
    "WS": "yes",
    "HR": "curly",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Hunter",
    "LN": "Burton",
    "BD": "2008",
    "HC": "brown",
    "EC": "green",
    "HT": "5",
    "SC": "white",
    "NS": "1",
    "PR": "married",
    "NG": "4",
    "HA": "50 chelsea view drive",
    "BF": "Peter McDonald",
    "IN": ["music","gaming","star wars"],
    "GL": "no",
    "SX": "male",
    "AT": "cats",
    "SP": "no",
    "WS": "yes",
    "HR": "wavy",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Jesse",
    "LN": "Scott",
    "BD": "2008",
    "HC": "brown",
    "EC": "brown",
    "HT": "6",
    "SC": "black",
    "NS": "1",
    "PR": "divorced",
    "NG": "0",
    "HA": "136 chelsea view drive",
    "BF": "Brayden Fitzgerald",
    "IN": ["b*obs","bum","music"],
    "GL": "no",
    "SX": "male",
    "AT": "dogs",
    "SP": "yes",
    "WS": "no",
    "HR": "curly",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Connor",
    "LN": "Potgeiter",
    "BD": "2009",
    "HC": "dirty blonde",
    "EC": "green",
    "HT": "5",
    "SC": "white",
    "NS": "1",
    "PR": "married",
    "NG": "2",
    "HA": "7 oruamo place",
    "BF": "Jesse Scott",
    "IN": ["music","weed","Jesse"],
    "GL": "no",
    "SX": "male",
    "AT": "dogs",
    "SP": "",
    "WS": "",
    "HR": "",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Azlin",
    "LN": "Grooby",
    "BD": "2008",
    "HC": "black",
    "EC": "brown",
    "HT": "6",
    "SC": "white",
    "NS": "5",
    "PR": "broken up",
    "NG": "2",
    "HA": "16 paetahi lane",
    "BF": "Phillip Alona",
    "IN": ["sleeping","gym","gaming"],
    "GL": "no",
    "SX": "male",
    "AT": "",
    "SP": "",
    "WS": "",
    "HR": "",
    "EA": "",
    "Match": [0]
  },
  {
    "FN": "Jett",
    "LN": "Sweeney",
    "BD": "2008",
    "HC": "brown",
    "EC": "green",
    "HT": "5",
    "SC": "white",
    "NS": "4",
    "PR": "divorced",
    "NG": "3",
    "HA": "54 kittiwake drive",
    "BF": "Fynn",
    "IN": ["Fynn", "bed rotting", "music"],
    "GL": "no",
    "SX": "female",
    "AT": "cats",
    "SP": "no",
    "WS": "no",
    "HR": "wavy",
    "EA": "pierced",
    "Match": [0]
  },
  {
    "FN": "Emma",
    "LN": "Louis",
    "BD": "2008", 
    "HC": "Black", 
    "EC": "Brown",
    "HT": "5",
    "SC": "Yellow",
    "NS": "0", 
    "PR": "Married",
    "NG": "3", 
    "HA": "", 
    "BF": "Igor", 
    "IN": ["gaming", "horror movies", "drawing"], 
    "GL": "no",
    "SX": "Female",
    "AT": "cats",
    "SP": "no",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "David",
    "LN": "Clarke",
    "BD": "1968",
    "HC": "Grey", 
    "EC": "Blue",
    "HT": "6",
    "SC": "White",
    "NS": "3", 
    "PR": "Married", 
    "NG": "0", 
    "HA": "Beach Haven",
    "BF": "Mrs. Clarke", 
    "IN": ["football", "gadgets", "rubik's cubes"], 
    "GL": "yes", 
    "SX": "Male",
    "AT": "cats",
    "SP": "yes",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Varen",
    "LN": "Wilson",
    "BD": "2008",
    "HC": "Brown",
    "EC": "Brown",
    "HT": "6",
    "SC": "white",
    "NS": "0",
    "PR": "dating",
    "NG": "3",
    "HA": "Hillcrest Avenue",
    "BF": "Brodie Tawhai",
    "IN": ["science", "movies", "gaming"],
    "GL": "no",
    "SX": "Male",
    "AT": "dogs",
    "SP": "no",
    "WS": "yes",
    "HR": "wavy",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Allan",
    "LN": "Thomas",
    "BD": "2008",
    "HC": "Black",
    "EC": "Brown",
    "HT": "6",
    "SC": "Brown",
    "NS": "1",
    "PR": "Married",
    "NG": "2",
    "HA": "2/2 MCdowell",
    "BF": "Hunter Burton",
    "IN": ["music", "movies", "gaming"],
    "GL": "no",
    "SX": "Male",
    "AT": "dogs",
    "SP": "yes",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Shyaw",
    "LN": "Saeed",
    "BD": "2009",
    "HC": "black",
    "EC": "Brown",
    "HT": "5",
    "SC": "#a3892a",
    "NS": "1",
    "PR": "married",
    "NG": "2",
    "HA": "Sispara Place",
    "BF": "Callum Puddle",
    "IN": ["football", "chess", "callum puddle"],
    "GL": "no",
    "SX": "Male",
    "AT": "cats",
    "SP": "yes",
    "WS": "no",
    "HR": "curly",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Liam",
    "LN": "Salton",
    "BD": "2008",
    "HC": "orange",
    "EC": "blue",
    "HT": "5",
    "SC": "white",
    "NS": "2",
    "PR": "married",
    "NG": "4",
    "HA": "16 Tamahere Drive",
    "BF": "",
    "IN": ["whacking", "fortnite", "roblox"],
    "GL": "no",
    "SX": "Male",
    "AT": "cat",
    "SP": "yes",
    "WS": "no",
    "HR": "straight",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Callum",
    "LN": "Puddle",
    "BD": "2008",
    "HC": "black",
    "EC": "brown",
    "HT": "5",
    "SC": "yellow",
    "NS": "3",
    "PR": "married",
    "NG": "4",
    "HA": "16 Tamahere Drive",
    "BF": "",
    "IN": ["music", "food", "cats"],
    "GL": "no",
    "SX": "Male",
    "AT": "cat",
    "SP": "yes",
    "WS": "yes",
    "HR": "curly",
    "EA": "unpierced",
    "Match": [0]
  },
  {
    "FN": "Peter",
    "LN": "Macdonald",
    "BD": "2008",
    "HC": "brown",
    "EC": "blue",
    "HT": "5",
    "SC": "white",
    "NS": "1",
    "PR": "divorced",
    "NG": "3",
    "HA": "41A Aeroview drive",
    "BF": "Hunter Burton",
    "IN": ["Guitar", "kickboxing", "band"],
    "GL": "no",
    "SX": "Male",
    "AT": "dogs",
    "SP": "no",
    "WS": "yes",
    "HR": "wavy",
    "EA": "pierced",
    "Match": [0]
  },
  {
    "FN": "Isaac",
    "LN": "Dutta-Gupta",
    "BD": "2009",
    "HC": "black",
    "EC": "dark brown",
    "HT": "5",
    "SC": "brown",
    "NS": "1",
    "PR": "divorced",
    "NG": "4",
    "HA": "25 sispara place",
    "BF": "John Martin Roy",
    "IN": ["women", "anime", "sport"],
    "GL": "no",
    "SX": "Male",
    "AT": "cats",
    "SP": "yes",
    "WS": "no",
    "HR": "stright",
    "EA": "pierced",
    "Match": [0]
  },
  {
    "FN": "Zac",
    "LN": "Parker-Hansen",
    "BD": "2008",
    "HC": "brown",
    "EC": "green",
    "HT": "6",
    "SC": "white",
    "NS": "2",
    "PR": "divorced",
    "NG": "3",
    "HA": "22 beulah ave/78 avocado lane",
    "BF": "John Martin Roy",
    "IN": ["music", "food", "sex"],
    "GL": "no",
    "SX": "Male",
    "AT": "cats",
    "SP": "no",
    "WS": "yes",
    "HR": "wavy",
    "EA": "unpierced",
    "Match": [0]
  }
]

// If there are user additions
if(localStorage.getItem("user-additions")){
  let person = localStorage.getItem("user-additions").split('},')

  // Add user additions to people list
  for(var i = 0; i < person.length; i++){
    if(i != person.length-1){
      people.push(JSON.parse(person[i] + "}"))
    }else{
      people.push(JSON.parse(person[i]))
    }
    
  }  

// Otherwise
}else{

  // Add me (Fynn Bisschoff), to user additions
  localStorage.setItem("user-additions", '{"FN": "Fynn","LN": "Bisschoff","BD": "2008","HC": "brown","EC": "hazel","HT": "6","SC": "white","NS": "1","PR": "married","NG": "4","HA": "45 kittiwake drive","BF": "Jett","IN": ["Jett", "puzzles", "music"],"GL": "no","SX": "male","AT": "Dogs","SP": "no","WS": "no","HR": "wavy","EA": "unpierced","Match": [0]}')
  people.push(JSON.parse(localStorage.getItem("user-additions")))
}

